kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: siri-demo
  namespace: siri-demo
  selfLink: /apis/apps.openshift.io/v1/namespaces/siri-demo/deploymentconfigs/siri-demo
  uid: b04c6daf-ac52-11e9-9305-0a580a8000c1
  resourceVersion: '3738234'
  generation: 13
  creationTimestamp: '2019-07-22T07:31:15Z'
  labels:
    app: siri-demo
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - siri-demo
        from:
          kind: ImageStreamTag
          namespace: siri-demo
          name: 'siri-demo:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/siri-demo/siri-demo@sha256:a475a69f7d8fb382fcad5652aadc2113c63fef31c600fdc71a055f63bb430d3c
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: siri-demo
    deploymentconfig: siri-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: siri-demo
        deploymentconfig: siri-demo
    spec:
      containers:
        - name: siri-demo
          image: >-
            image-registry.openshift-image-registry.svc:5000/siri-demo/siri-demo@sha256:a475a69f7d8fb382fcad5652aadc2113c63fef31c600fdc71a055f63bb430d3c
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-Xms512m -Xmx640m -Duser.timezone=Europe/Paris'
            - name: DAY_OF_WEEK
              value: '7'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 13
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 12
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2019-07-22T09:32:23Z'
      lastTransitionTime: '2019-07-22T09:32:23Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2019-07-22T09:32:26Z'
      lastTransitionTime: '2019-07-22T09:32:23Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "siri-demo-12" successfully rolled out
  replicas: 1
  readyReplicas: 1
